from enum import Enum

class Mode(Enum):
    TIME_ATTACK='t'
    POINT_ATTACK='p'
    SURVIVAL='s'

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
MAX_PLAYER_SPEED= 300
PLAYER_ACCEL=15
PLAYER_SHOOT_SPEED = 500
SHOT_RADIUS = 5
SHOT_DISTANCE = .5
PLAYER_SHOOT_COOLDOWN = .3
ASTEROID_POINTS = 100
FRAMES_PER_SECOND = 30
POWERUP_SPAWN_RATE= 8#spawn every 20 seconds
TIME_LIMIT = 60
HIT_PENALTY = 10#per frame, should probably have a flat 10% penalty or so but give iframes
SCORE_GOAL = 1000 # score goal for time attack
EMBLEM_TIME=75
PLAYER_COLOR=(255,255,255)
PLAYER_COLOR_HIT=(0, 0, 255)
ASTEROID_LIMIT=100
ASTEROID_EXPLODE_TIMER=10#asteroids explode after 10 seconds
